//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoVWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Availables = new HashSet<Available>();
            this.Pictures = new HashSet<Picture>();
            this.PushContacts = new HashSet<PushContact>();
            this.Tokens = new HashSet<Token>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public string account { get; set; }
        public bool email_message { get; set; }
        public bool text_message { get; set; }
        public bool app_message { get; set; }
        public bool changed { get; set; }
    
        public virtual ICollection<Available> Availables { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual ICollection<PushContact> PushContacts { get; set; }
        public virtual ICollection<Token> Tokens { get; set; }
    }
}
